settings:
  title: 'Status Page'
  url: 'https://stat.firmant.me' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id:blog
    name: Blog
    url: 'https://firmant.me'
    method: GET
    expectStatus: 200
    linkable: true
    
  - id: one-api
    name: One API
    url: 'https://api.firmant.me'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: sowayomi
    name: Sowayomi
    url: 'https://manga.firmant.me/'
    method: GET
    expectStatus: 200

  - id: npm
    name: Nginx Proxy Manager
    url: 'https://npm.firmant.me/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200

  - id: docker
    name: Dockge
    url: 'https://docker.firmant.me/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200
    
